import type { Metadata } from "next";
import "./globals.css";
import Main from "@/components/Main";

export const metadata: Metadata = {
  title: "todo app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Main>{children}</Main>
      </body>
    </html>
  );
}
